spring:
  application:
     name: spring-kafka-workshop-producer
  devtools:
    livereload:
      port: 35729

api:
  swapi:
    base-url: https://www.swapi.tech/api/
  workshop-consumer:
    base-url: http://localhost:8081/starwars
