spring:
  application:
     name: spring-kafka-workshop-producer
  devtools:
    livereload:
      port: 35729
  kafka:
    bootstrap-servers: http://host.docker.internal:9092
    topic:
      name: starwars
      partition-count: 1
      replication-factor: 1
    producer:
      bootstrap-servers: http://host.docker.internal:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: spring-kafka-workshop-producer


api:
  swapi:
    base-url: https://www.swapi.tech/api/
  workshop-consumer:
    base-url: http://localhost:8081/starwars
